### ISSUE TITLE
path.op在19版本以下要如何实现

### ISSUE THREAD

**Issue by apkcore** [Solartisan/WaveSideBar#1]
求解

**Comment by solartcc** [comment]
可以考虑用Xfermode来实现，不确定可行度有多高，这个项目就是当时一时兴起做的，没有考虑向下兼容，有兴趣你可以试试~ 如果后面有时间我也会再把兼容性这块解决掉，谢谢您的关注！

**Comment by supersugar** [comment]
正想用作者这个控件呢,但是这个兼容性问题不知道怎么解决,但是...貌似把那一行出错的注释掉...也是可以正常运行的- -

**Comment by solartcc** [comment]
op的操作是为了去重圆形Path以及波浪Path的重叠，注释掉不影响使用，只是可以看到有重叠的部分，这部分向下兼容，一直没有时间细想。

**Comment by AngelYHY** [comment]
public static final String DATA = "[{"pys":"A","type":1},{"pys":"B","type":1},{"pys":"C","type":1},{"pys":"D","type":1},{"pys":"E","type":1},{"pys":"F","type":1},{"pys":"G","type":1},      请问下  这个什么意思？？

**Comment by solartcc** [comment]
仅仅是字母pinned的json数据而已，type类型是为了区分字母与城市名的不同布局。

**Comment by AngelYHY** [comment]
我懂了~，~   谢谢了     真是6翻了~~
