### ISSUE TITLE
关于兼容19以下的版本

### ISSUE THREAD

**Issue by loonggg** [Solartisan/WaveSideBar#10]
我想知道修改的地方在哪？能否指出来吗？

**Comment by solartcc** [comment]
这行代码BallPath.op(mWavePath, Path.Op.DIFFERENCE) api有版本要求，兼容性主要是因为波形和圆形重叠的部分采用op操作来处理。简单适配可以通过sdk版本判断19以下不执行这行代码，不影响功能使用，只是19以下的版本交互上可能不那么美观。真正处理兼容性可以考虑从19以下版本如何处理Path重叠来着手。

**Comment by solartcc** [comment]
目前已经按照版本暂时先处理了
