### ISSUE TITLE
从上往下滑动的时候，似乎有些问题

### ISSUE THREAD

**Issue by sunflowerseat** [Solartisan/WaveSideBar#5]

**Comment by sunflowerseat** [comment]
scrolltoPosition ，从上往下的时候 不是显示在第一行，而是最后一行

**Comment by solartcc** [comment]
这个不是控件本身的问题，是RecyclerView没有像ListView一样支持setSelection()，demo只是单纯的演示，并没有对这块做细节处理。

**Comment by sunflowerseat** [comment]
嗯， 已经解决了。

**Comment by sunflowerseat** [comment]
mRecyclerView.scrollToPosition(pos);
LinearLayoutManager mLayoutManager =
                            (LinearLayoutManager) mRecyclerView.getLayoutManager();
mLayoutManager.scrollToPositionWithOffset(pos, 0);
改成这样就可以了。 的确是recycler的问题

**Comment by solartcc** [comment]
棒！最近确实很少能挤出时间来看看这个项目，本来这个项目是一时兴致写的，没想到却得到大家那么多star，下一步我会花点时间在适配上^_^
