### ISSUE TITLE
提问题咯

### ISSUE THREAD

**Issue by AngelYHY** [Solartisan/WaveSideBar#8]
键盘 弹起之后   后来   收回之后     右边那个变小了一半     这是什么原因 ？？？ 
![306b97550e009aad01d5b52b11dfffd9](https://cloud.githubusercontent.com/assets/19568255/17685824/15d9c128-639a-11e6-93fb-496dbf5a3c25.jpg)
![be98bb290e533e5e71f37bbbcb27af65](https://cloud.githubusercontent.com/assets/19568255/17685825/1605059a-639a-11e6-8443-e8e7dce94289.jpg)

**Comment by solartcc** [comment]
目测是键盘弹出和收回时，mHeight的高度获取方式不准确，临时方案Activity设置android:windowSoftInputMode="adjustPan"，稍后会修复这个bug。
