### ISSUE TITLE
有时候绿色的小球会出现在屏幕的左上角

### ISSUE THREAD

**Issue by supersugar** [Solartisan/WaveSideBar#9]
刚进入界面的时候,左上角有绿色的小球,只有下半圆,滑动列表以后就正常了
代码中注释掉了mBallPath.op(mWavePath, Path.Op.DIFFERENCE);
不知道是不是这个影响

**Comment by solartcc** [comment]
我找时间定位下问题，也欢迎PR

**Comment by dyxin00** [comment]
这个问题有可能是因为 onMeasure  使用 getWidth 获取 width 时 有可能会出现获取不到的问题，建议使用 getMeasuredWidth 开获取 width。

**Comment by yaochangliang159** [comment]
同问这个问题
